name: Build

# Controls when the workflow will run
on:
#  workflow_dispatch
  push:
    branches:
      - 'main'
#      - 'dev'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'main'
#      - 'dev'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
#      -
#        name: Set up QEMU
#        uses: docker/setup-qemu-action@v2
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            Chris591/Cups-Server
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
      -
        name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/arm64/v8


#        name: Build
#        uses: docker/bake-action@v2
#        with:
#          platforms: linux/arm64/v8
#          context: .
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}
#          files: |
#            ./docker-bake.hcl
#            ${{ steps.meta.outputs.bake-file }}
#          targets: build