name: Build

# Controls when the workflow will run
on:
#  workflow_dispatch
  push:
    branches:
      - 'main'
#      - 'dev'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'main'
#      - 'dev'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@f3c664df7af409cb4873aa5068053ba9d61a57b6 #v2.6.0
        with:
          cosign-release: 'v1.13.1'

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: chris591/cups-server:latest
          platforms: linux/arm64/v8


      # Sign the resulting Docker image digest except on PRs.
      # This will only write to the public Rekor transparency log when the Docker
      # repository is public to avoid leaking data.  If you would like to publish
      # transparency data even for private images, pass --force to cosign below.
      # https://github.com/sigstore/cosign
      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          COSIGN_EXPERIMENTAL: "true"
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: echo "chris591/cups-server:latest" | xargs -I {} cosign sign {}@${{ steps.build-and-push.outputs.digest }}

#        name: Build
#        uses: docker/bake-action@v2
#        with:
#          platforms: linux/arm64/v8
#          context: .
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}
##          files: |
##            ./docker-bake.hcl
##            ${{ steps.meta.outputs.bake-file }}
#          targets: build